title: Vražedné záhady slečny Fisherovej alebo dáma detektívka
baseURL: https://barbies.github.io/hugo-start/
languageCode: cs-cz
publishDir: docs


menu:
  main:
    - name: Homepage
      url: /
      weight: 10
    - name: Archive
      identifier: post
      url: /post/
      weight: 20



